baseURL = "https://dev-n-gine.akkey.net/"
languageCode = "ja"
title = "dev.Engine"
hasCJKLanguage = true
googleAnalytics = "UA-87724467-2"
[Params]
  since = 2018
  keyword = "dev.Engine"
  description = "プログラミングで日々学んだことを綴るブログ"
[blackfriday]
  extensions = ["hardLineBreak"]
[[menu.main]]
  name = "/img/github.png"
  weight = -110
  url = "https://github.com/akkey247"
[[menu.main]]
  name = "/img/akkey.png"
  weight = -100
  url = "http://dev-n-gine.akkey.net/"